CREATE USER conferences WITH PASSWORD 'conferences';

-- Create the database:
CREATE DATABASE conferences WITH OWNER =conferences
    LC_COLLATE ='en_US.utf8'
    LC_CTYPE ='en_US.utf8'
    ENCODING ='UTF8'
    TEMPLATE =template0;

DROP TABLE USER_ROLES;
DROP TABLE ROLES;
DROP TABLE USERS_CONFERENCES;
DROP TABLE USERS;
DROP TABLE CONFERENCES;

CREATE TABLE USERS
(
    USER_ID          SERIAL PRIMARY KEY,
    FIRST_NAME       VARCHAR(50)  NOT NULL,
    LAST_NAME        VARCHAR(50)  NOT NULL,
    THIRD_NAME       VARCHAR(50),
    PASSWORD         VARCHAR(200) NOT NULL,
    DATE_OF_BIRTH    DATE         NOT NULL,
    GENDER           CHAR         NOT NULL,
    PHONE            VARCHAR(50),
    EMAIL            VARCHAR(255) NOT NULL UNIQUE,
    ORGANISATION     VARCHAR(70),
    UNIVERSITY       VARCHAR(100),
    DEPARTMENT       VARCHAR(100),
    EDUCATION_TYPE   VARCHAR(30),
    EDUCATION_STATUS VARCHAR(30),
    GRADUATION_YEAR  VARCHAR(4)
);

CREATE TABLE CONFERENCES
(
    CONFERENCE_ID      SERIAL PRIMARY KEY,
    TITLE              VARCHAR(100) NOT NULL,
    SHORT_DESCRIPTION  VARCHAR(100) NOT NULL,
    FULL_DESCRIPTION   VARCHAR(4000),
    CONF_LOCATION      VARCHAR(100) NOT NULL,
    ORGANIZER          VARCHAR(100) NOT NULL,
    CONTACTS           VARCHAR(100) NOT NULL,
    START_DATE         DATE         NOT NULL,
    END_DATE           DATE         NOT NULL,
    START_REGISTRATION DATE         NOT NULL,
    END_REGISTRATION   DATE         NOT NULL,
    CREATED_BY         INT          NOT NULL
);


CREATE TABLE USERS_CONFERENCES
(
    USER_CONFERENCE_ID SERIAL PRIMARY KEY,
    USER_ID            INT NOT NULL,
    CONFERENCE_ID      INT NOT NULL,
    REPORT_FILE_PATH   VARCHAR(4000),
    REVIEW_FILE_PATH   VARCHAR(4000),
    REPORT_STATUS      VARCHAR(10),
    ROLE            VARCHAR(20) NOT NULL
);

CREATE TABLE ROLES
(
    ID   SERIAL PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE USER_ROLES
(
    USER_ROLE_ID       SERIAL PRIMARY KEY,
    USER_ID            INT,
    ROLE_ID            INT
);

ALTER TABLE users_conferences
    ADD CONSTRAINT FK_USERS_CONFERENCES_ON_CONFERENCE FOREIGN KEY (conference_id) REFERENCES conferences (conference_id) ON DELETE CASCADE;

ALTER TABLE users_conferences
    ADD CONSTRAINT FK_USERS_CONFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE USER_ROLES
    ADD CONSTRAINT FK_USER_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE;

ALTER TABLE USER_ROLES
    ADD CONSTRAINT FK_USER_ROLES_ON_USER FOREIGN KEY (USER_ID) REFERENCES users (user_id) ON DELETE CASCADE;


insert into ROLES(ID, NAME)
values (1, 'Admin');
insert into ROLES(ID, NAME)
values (2, 'User');
commit;
